###
###   device api: exchange the same message payload as per the mqtt protocol
###   "sign" = md5(messageId + key + timestamp)

POST http://192.168.10.13/config HTTP/1.1
Content-Type: application/json

{
    "header":{
        "from":"",
        "messageId":"",
        "method":"GET",
        "namespace":"Appliance.Hub.Mts100.All",
        "payloadVersion":1,
        "sign":"b2f7be905c2e36511b5207dc6b313d02",
        "timestamp": 1622314429
        },
    "payload":{
      "all": []
    }
}

###
POST http://192.168.10.21/config HTTP/1.1
Content-Type: application/json

{
    "header":{
        "from":"",
        "messageId":"1",
        "method":"SET",
        "namespace":"Appliance.Config.Key",
        "payloadVersion":1,
        "sign":"f3030ba98178e1afc9b47b97dad18221",
        "timestamp":1617116856
        },
    "payload":{
      "key":{
        "gateway":{
          "host": "192.168.10.11",
          "port": 8883,
          "secondHost": "192.168.10.11",
          "secondPort": 8883
        },
        "key": "",
        "userId": "0"
      }
    }
}
###
POST http://192.168.10.14/config HTTP/1.1
Content-Type: application/json

{
    "header": {
        "messageId": "",
        "namespace": "Appliance.Control.ToggleX",
        "method": "GET",
        "payloadVersion": 1,
        "from": "",
        "timestamp": 0,
        "timestampMs": 60,
        "sign": "cfcd208495d565ef66e7dff9f98764da"
    },
    "payload": {
        "togglex": [ { "channel": 1}]
    }
}
###
POST http://192.168.10.21/config HTTP/1.1
Content-Type: application/json

{
  "header": {
    "messageId": "",
    "namespace": "Appliance.Config.Key",
    "method": "SET",
    "payloadVersion": 1,
    "timestamp": 0,
    "sign": "cfcd208495d565ef66e7dff9f98764da"
  },
  "payload": {
     "key" : {
       "gateway": {
         "host": "192.168.10.11",
         "port": 8883,
         "secondHost": "192.168.10.11",
         "secondPort": 8883
       },
       "key": "",
       "userId": ""
     }
  }
}
###
POST http://192.168.10.14/config HTTP/1.1
Content-Type: application/json

{
    "header": {
        "messageId":"",
        "namespace":"Appliance.Control.ToggleX",
        "method":"GET",
        "from":"",
        "payloadVersion":1,
        "timestamp": 0,
        "timestampMs": 60,
        "sign":"cfcd208495d565ef66e7dff9f98764da"
        },
    "payload": {
      "togglex" : []
    }
}

###
POST http://192.168.10.14/config HTTP/1.1
Content-Type: application/json

{
    "header":{
        "from":"",
        "messageId":"",
        "method":"GET",
        "namespace":"Appliance.System.All",
        "payloadVersion":1,
        "sign":"cfcd208495d565ef66e7dff9f98764da",
        "timestamp": 0
        },
    "payload":{
    }
}
