#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# add support for ffmpeg/libpcap (ms python container lacks these by default)
apt update
apt -y install ffmpeg
apt -y install libpcap-dev
apt -y install libturbojpeg0

python3 -m pip install --upgrade pip
python3 -m pip install --requirement requirements_test.txt

curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

# add go2rtc binary (needed from HA 2024.11) at least until we're using an image lacking it
cd /usr/local/bin
wget https://github.com/AlexxIT/go2rtc/releases/download/v1.9.9/go2rtc_linux_amd64
chmod +x go2rtc_linux_amd64
mv go2rtc_linux_amd64 go2rtc