#curl -X POST -H "Content-Type: application/json" -d '{"header":{"from":"","messageId":"","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"cfcd208495d565ef66e7dff9f98764da","timestamp":0},"payload":{}}' http://192.168.10.20/config
POST http://192.168.10.20/config HTTP/1.1
Content-Type: application/json

{
    "header":{
        "from":"",
        "messageId":"",
        "method":"GET",
        "namespace":"Appliance.System.All",
        "payloadVersion":1,
        "sign":"cfcd208495d565ef66e7dff9f98764da",
        "timestamp":0
        },
    "payload":{}
}

###
POST http://192.168.10.20/config HTTP/1.1
Content-Type: application/json

{
    "header":{
        "from":"",
        "messageId":"",
        "method":"GET",
        "namespace":"Appliance.System.Online",
        "payloadVersion":1,
        "sign":"cfcd208495d565ef66e7dff9f98764da",
        "timestamp":0
        },
    "payload":{}
}
###
POST http://192.168.10.20/config HTTP/1.1
Content-Type: application/json

{
  "header": {
    "messageId": "",
    "namespace": "Appliance.Control.ConsumptionX",
    "method": "GET",
    "payloadVersion": 1,
    "timestamp": 0,
    "sign": "cfcd208495d565ef66e7dff9f98764da"
  },
  "payload": {
     "channel" : 0
  }
}